import type { IData, IDataColumn, ListSettings } from './types';

export const SAMPLE_COLS: IDataColumn[] = [
    { field: 'code', type: 'string', name: 'code', description: 'Код', len: 20, hasSorting: true, show: true, cellWidth: 110 },
    { field: 'name', type: 'string', name: 'name', description: 'Наименование', len: 120, hasSorting: true, show: true, cellFlexGrow: true },
    { field: 'category', type: 'string', name: 'category', description: 'Категория', len: 40, hasSorting: true, show: true, cellWidth: 140 },
    { field: 'kind', type: 'string', name: 'kind', description: 'Вид', len: 40, hasSorting: true, show: true, cellWidth: 150 },
    { field: 'status', type: 'string', name: 'status', description: 'Статус', len: 20, hasSorting: true, show: true, cellWidth: 120 },
    { field: 'price', type: 'number', name: 'price', description: 'Цена', len: 12, hasSorting: true, show: true, cellWidth: 100 },
    { field: 'stock', type: 'number', name: 'stock', description: 'Остаток', len: 12, hasSorting: true, show: true, cellWidth: 100 },
    { field: 'createdAt', type: 'date', name: 'createdAt', description: 'Создан', len: 24, hasSorting: true, show: true, cellWidth: 120 },
];

export const SAMPLE_DATA: IData = {
    count: 18,
    refs: {
        kind: {
            nom: 'Номенклатура',
            svc: 'Услуга',
        },
        status: {
            active: 'Активен',
            archived: 'Архив',
        },
    },
    cols: SAMPLE_COLS,
    rows: [
        { id: '1', code: 'N-100', name: 'Болт М8', category: 'A', kind: 'nom', status: 'active', price: 120, stock: 40, createdAt: '2024-01-12' },
        { id: '2', code: 'N-101', name: 'Гайка М8', category: 'A', kind: 'nom', status: 'active', price: 80, stock: 12, createdAt: '2024-02-03' },
        { id: '3', code: 'N-102', name: 'Шайба 8', category: 'A', kind: 'nom', status: 'active', price: 210, stock: -4, createdAt: '2024-03-18' },
        { id: '4', code: 'N-200', name: 'Кабель ВВГ', category: 'A', kind: 'nom', status: 'archived', price: 340, stock: 7, createdAt: '2023-11-02' },
        { id: '5', code: 'S-010', name: 'Монтаж щита', category: 'A', kind: 'svc', status: 'active', price: 450, stock: 0, createdAt: '2024-04-01' },
        { id: '6', code: 'S-011', name: 'Пусконаладка', category: 'A', kind: 'svc', status: 'active', price: 900, stock: 0, createdAt: '2024-04-09' },
        { id: '7', code: 'N-300', name: 'Лампа LED', category: 'B', kind: 'nom', status: 'active', price: 150, stock: 22, createdAt: '2024-05-14' },
        { id: '8', code: 'N-301', name: 'Плафон', category: 'B', kind: 'nom', status: 'active', price: 275, stock: -1, createdAt: '2024-05-20' },
        { id: '9', code: 'N-302', name: 'Выключатель', category: 'B', kind: 'nom', status: 'active', price: 99, stock: 18, createdAt: '2024-06-02' },
        { id: '10', code: 'S-020', name: 'Замена ламп', category: 'B', kind: 'svc', status: 'active', price: 320, stock: 0, createdAt: '2024-06-11' },
        { id: '11', code: 'S-021', name: 'Обследование', category: 'B', kind: 'svc', status: 'archived', price: 180, stock: 0, createdAt: '2023-09-30' },
        { id: '12', code: 'N-400', name: 'Стол офисный', category: 'C', kind: 'nom', status: 'active', price: 480, stock: 5, createdAt: '2024-07-01' },
        { id: '13', code: 'N-401', name: 'Стул', category: 'C', kind: 'nom', status: 'active', price: 190, stock: -8, createdAt: '2024-07-08' },
        { id: '14', code: 'N-402', name: 'Тумба', category: 'C', kind: 'nom', status: 'active', price: 610, stock: 2, createdAt: '2024-07-19' },
        { id: '15', code: 'S-030', name: 'Сборка мебели', category: 'C', kind: 'svc', status: 'active', price: 250, stock: 0, createdAt: '2024-08-03' },
        { id: '16', code: 'S-031', name: 'Доставка', category: 'C', kind: 'svc', status: 'active', price: 110, stock: 0, createdAt: '2024-08-12' },
        { id: '17', code: 'N-500', name: 'Краска белая', category: 'B', kind: 'nom', status: 'active', price: 430, stock: 9, createdAt: '2024-08-21' },
        { id: '18', code: 'N-501', name: 'Валик', category: 'B', kind: 'nom', status: 'active', price: 70, stock: 30, createdAt: '2024-08-28' },
    ],
};

export const SAMPLE_SETTINGS: ListSettings = {
    selectionNodes: [
        {
            id: 'sel-group-1',
            kind: 'group',
            logic: 'and',
            enabled: true,
            children: [
                {
                    id: 'sel-status-1',
                    kind: 'condition',
                    field: 'status',
                    comparison: 'eq',
                    value: 'Активен',
                    enabled: true,
                    useRange: false,
                },
            ],
        },
        {
            id: 'sel-price-1',
            kind: 'condition',
            field: 'price',
            comparison: 'between',
            value: ['100', '500'],
            enabled: true,
        },
    ],
    grouping: {
        selectedGroupFields: ['category', 'kind'],
        disabledGroupFields: [],
    },
    sort: {
        sortRules: [{ field: 'price', direction: 'DESC', enabled: true }],
        availableFields: SAMPLE_COLS.map((column) => ({
            id: column.field,
            label: column.description || column.name,
            value: column.field,
            isGroupLevel: false,
        })),
        fieldTypes: {
            price: 'number',
            stock: 'number',
            createdAt: 'date',
            name: 'string',
            category: 'string',
            kind: 'string',
            status: 'string',
            code: 'string',
        },
    },
    columnGroupingRoot: {
        id: 'root',
        kind: 'root',
        title: 'Список столбцов',
        children: [
            {
                id: 'group_1',
                kind: 'group',
                title: 'Цена',
                orientation: 'horizontal',
                enabled: true,
                width: 180,
                children: [{ id: 'col_price', kind: 'column', fieldId: 'price', enabled: true }],
            },
            { id: 'col_name', kind: 'column', fieldId: 'name', enabled: true, flexGrow: true },
            { id: 'col_category', kind: 'column', fieldId: 'category', enabled: true, width: 130 },
            { id: 'col_kind', kind: 'column', fieldId: 'kind', enabled: true, width: 150 },
            { id: 'col_status', kind: 'column', fieldId: 'status', enabled: true, width: 120 },
            { id: 'col_stock', kind: 'column', fieldId: 'stock', enabled: true, width: 110 },
            { id: 'col_createdAt', kind: 'column', fieldId: 'createdAt', enabled: true, width: 120 },
            { id: 'col_code', kind: 'column', fieldId: 'code', enabled: true, width: 110 },
        ],
    },
    conditionalFormattingRules: [
        {
            id: 'rule-1',
            enabled: true,
            presentation: 'Отрицательный остаток',
            appearance: { backgroundColor: '#f4515d', textColor: '#ffffff' },
            conditionNodes: [
                {
                    id: 'sel-stock-1',
                    kind: 'condition',
                    field: 'stock',
                    comparison: 'lt',
                    value: '0',
                    enabled: true,
                },
            ],
            targetFields: ['stock'],
            applyToSubstrings: true,
        },
        {
            id: 'rule-price-format',
            enabled: true,
            presentation: 'Цена: Ч=0.00',
            appearance: { format: 'Ч=0.00', horizontalAlign: 'right' },
            conditionNodes: [
                {
                    id: 'sel-price-filled',
                    kind: 'condition',
                    field: 'price',
                    comparison: 'filled',
                    value: '',
                    enabled: true,
                },
            ],
            targetFields: ['price'],
        },
        {
            id: 'rule-date-format',
            enabled: true,
            presentation: 'Дата: ДФ=дд.ММ.уууу',
            appearance: { format: 'ДФ=дд.ММ.уууу', horizontalAlign: 'center' },
            conditionNodes: [
                {
                    id: 'sel-date-filled',
                    kind: 'condition',
                    field: 'createdAt',
                    comparison: 'filled',
                    value: '',
                    enabled: true,
                },
            ],
            targetFields: ['createdAt'],
        },
        {
            id: 'rule-name-case',
            enabled: true,
            presentation: 'Имя: СГР=ВЕРХНИЙ (категория A)',
            appearance: { format: 'СГР=ВЕРХНИЙ', font: { bold: true } },
            conditionNodes: [
                {
                    id: 'sel-cat-a',
                    kind: 'condition',
                    field: 'category',
                    comparison: 'eq',
                    value: 'A',
                    enabled: true,
                },
            ],
            targetFields: ['name'],
        },
        {
            id: 'rule-status-font',
            enabled: true,
            presentation: 'Статус Архив: italic + strikethrough',
            appearance: { font: { italic: true, strikethrough: true }, textColor: '#8b97ab' },
            conditionNodes: [
                {
                    id: 'sel-status-arch',
                    kind: 'condition',
                    field: 'status',
                    comparison: 'eq',
                    value: 'Архив',
                    enabled: true,
                },
            ],
            targetFields: ['status'],
        },
        {
            id: 'rule-mark-negatives',
            enabled: true,
            presentation: 'Цена: markNegatives',
            appearance: { markNegatives: true },
            conditionNodes: [
                {
                    id: 'sel-price-any',
                    kind: 'condition',
                    field: 'price',
                    comparison: 'filled',
                    value: '',
                    enabled: true,
                },
            ],
            targetFields: ['price'],
        },
        {
            id: 'rule-incomplete',
            enabled: true,
            presentation: 'Код: markIncomplete',
            appearance: { markIncomplete: true },
            conditionNodes: [
                {
                    id: 'sel-code-empty',
                    kind: 'condition',
                    field: 'code',
                    comparison: 'empty',
                    value: '',
                    enabled: true,
                },
            ],
            targetFields: ['code'],
        },
        {
            id: 'rule-orientation',
            enabled: false,
            presentation: 'Код: textOrientation topToBottom',
            appearance: { textOrientation: 'topToBottom' },
            conditionNodes: [
                {
                    id: 'sel-code-filled',
                    kind: 'condition',
                    field: 'code',
                    comparison: 'filled',
                    value: '',
                    enabled: true,
                },
            ],
            targetFields: ['code'],
        },
        {
            id: 'rule-mirror',
            enabled: false,
            presentation: 'Имя: mirror horizontal',
            appearance: { mirror: 'horizontal' },
            conditionNodes: [
                {
                    id: 'sel-name-filled',
                    kind: 'condition',
                    field: 'name',
                    comparison: 'filled',
                    value: '',
                    enabled: true,
                },
            ],
            targetFields: ['name'],
        },
        {
            id: 'rule-replace-text',
            enabled: true,
            presentation: 'Остаток 0: text = нет',
            appearance: { text: 'нет', textColor: '#8b97ab' },
            conditionNodes: [
                {
                    id: 'sel-stock-zero',
                    kind: 'condition',
                    field: 'stock',
                    comparison: 'eq',
                    value: '0',
                    enabled: true,
                },
            ],
            targetFields: ['stock'],
        },
    ],
};
